Repository googleapis/nodejs-video-transcoder, pull requests merged in 2020-11, with the labels that each got.

#4 build: stop ignoring docs now that they're generated
  linkinator.config.json
  synth.metadata
Labels: cla: yes, context: none

#5 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#6 fix: do not modify options object, use defaultScopes
  package.json
  src/index.ts
  src/v1beta1/transcoder_service_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: automerge, cla: yes

#15 docs: add samples to README
  .kokoro/samples-test.sh
  README.md
  protos/protos.json
  samples/README.md
  src/v1beta1/transcoder_service_client.ts
  synth.metadata
Labels: cla: yes, context: none

#16 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: full
