Repository googleapis/nodejs-video-transcoder, pull requests merged in 2020-12, with the labels that each got.

#17 chore: generate GAPIC metadata JSON file
  src/v1beta1/gapic_metadata.json
  synth.metadata
Labels: cla: yes, context: full

#18 build: add codeowners for samples
  .github/CODEOWNERS
Labels: cla: yes, samples

#19 docs: add instructions for authenticating for system tests
  CONTRIBUTING.md
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#20 docs: put FPS table in code block
  protos/google/cloud/video/transcoder/v1beta1/resources.proto
  synth.metadata
Labels: cla: yes, context: full
