Repository googleapis/nodejs-video-transcoder, pull requests merged in 2021-03, with the labels that each got.

#29 build: adds UNORDERED_LIST enum
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: cla: yes, context: none

#38 build: update gapic-generator-typescript to v1.2.10.
  synth.metadata
  webpack.config.js
Labels: api: transcoder, automerge, cla: yes, context: full

#32 meta: exclude custom CODEOWNERS
  synth.py
Labels: api: transcoder, cla: yes

#42 docs: add new samples to README
  README.md
  samples/README.md
  synth.metadata
Labels: api: transcoder, cla: yes, context: none

#43 feat: add spritesheet samples and tests. Remove unneeded list jobs ca…
  samples/createJobWithPeriodicImagesSpritesheet.js
  samples/createJobWithSetNumberImagesSpritesheet.js
  samples/test/transcoder.test.js
Labels: api: transcoder, cla: yes, samples

#46 docs: additional samples added to README
  README.md
  samples/README.md
  synth.metadata
Labels: api: transcoder, cla: yes, context: none
