Repository googleapis/nodejs-video-transcoder, pull requests merged in 2021-08, with the labels that each got.

#94 chore(nodejs): update client ref docs link in metadata
  .repo-metadata.json
  README.md
Labels: api: transcoder, automerge, cla: yes

#100 fix(deps): google-gax v2.24.1
  package.json
Labels: automerge, cla: yes, api: transcoder

#102 build: update CODEOWNERS manually
  .github/CODEOWNERS
Labels: cla: yes, api: transcoder

#99 feat: update Transcoder API samples to v1
  README.md
  samples/createJobFromAdHoc.js
  samples/createJobFromPreset.js
  samples/createJobFromTemplate.js
  samples/createJobTemplate.js
  samples/createJobWithAnimatedOverlay.js
  samples/createJobWithPeriodicImagesSpritesheet.js
  samples/createJobWithSetNumberImagesSpritesheet.js
  samples/createJobWithStaticOverlay.js
  samples/deleteJob.js
  samples/deleteJobTemplate.js
  samples/getJob.js
  samples/getJobState.js
  samples/getJobTemplate.js
  samples/listJobTemplates.js
  samples/listJobs.js
  samples/quickstart.js
  samples/test/transcoder.test.js
Labels: cla: yes, samples, api: transcoder
